name = "u: strong ends, weak center"

[initial_values]
u = 0.0
v = 0.0

[[perturbations]]
variable = "u"
position = 0.0
width_min_fraction = 0.06
width_max_fraction = 0.13
height_min = 2.0
height_max = 4.0

[[perturbations]]
variable = "u"
position = 0.5
width_min_fraction = 0.03
width_max_fraction = 0.06
height_min = 1.2
height_max = 2.3

[[perturbations]]
variable = "u"
position = 1.0
width_min_fraction = 0.06
width_max_fraction = 0.13
height_min = 2.0
height_max = 4.0
