name = "u: left / center / right"

[initial_values]
u = 0.0
v = 0.0

[[perturbations]]
variable = "u"
position = 0.0
width_min_fraction = 0.13
width_max_fraction = 0.25
height_min = 1.0
height_max = 2.0

[[perturbations]]
variable = "u"
position = 0.5
width_min_fraction = 0.13
width_max_fraction = 0.25
height_min = 1.0
height_max = 2.0

[[perturbations]]
variable = "u"
position = 1.0
width_min_fraction = 0.13
width_max_fraction = 0.25
height_min = 1.0
height_max = 2.0
